name: veli_flutter
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.19.4 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  bubble:
  intl:
  flutter_native_splash: ^2.3.3
  fluttertoast: 8.0.9
  google_maps_flutter: ^2.5.0
  http: ^1.1.0
  need_resume: ^1.0.7+1
  page_transition: ^2.1.0
  readmore: ^2.2.0 #tự động tóm tắt và hiển thị nội dung với tính năng 'Xem thêm'
  shared_preferences: ^2.2.1
  snippet_coder_utils: ^1.0.14 # customUI (dropdown, textbbox, button)
  socket_io_client: ^2.0.3+1
  url_launcher: ^6.1.14 # mở các url bên ngoài ứng dụng
  provider: ^6.0.5
  image_picker: ^0.8.9
  http_parser: ^4.0.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
